apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c5lcbvf6f-java-quarkus
  janus-idp.io/tekton: c5lcbvf6f-java-quarkus
  backstage.io/kubernetes-id: c5lcbvf6f-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c5lcbvf6f-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
